### PR TITLE
Fixed installation script under Windows

### PR DESCRIPTION
**Pull request by wjdob**
Corrected PowerShell installation script by adding features of:

-     Automatic cleanup of obsolete/mislocated .bat wrapper.
-     Automatic cleanup of PATH.
-     Fixed adding realme-ota to PATH, previously Add-Path function was not called resulting in installation failure.
-     Fixed handling of Python/Pip locations - previously the script assumed Python is installed in Program Files.
-     Added dependencies install for Requests and Pycryptodome Python modules.
-     Added hotfix for Lib\site-packages\crypto -> Lib\site-packages\Crypto folder naming.
-     Added .bat wrapper as part of package and automatic adjustment of "cd" command.

I adjusted README.MD and Install.ps1 to hyperlink to my fork, so feel free to change it back to master :)

### CODE REVIEW

**Comment by R0rt1z2** [comment]
Thank you very much! I was planning to fix the script sooner or later but I see you went ahead ;) I've applied the changes manually (keeping your authorship), hope you don't mind.

**Comment by wjdob** [comment]
Not a problem, glad to help :) One thing I noticed is that you have merged the .bat wrapper into a main directory. The installation script checks for the .bat wrapper inside the realme_ota folder, so you may want to move it there :)

**Comment by R0rt1z2** [comment]
Should be fixed now!

**Comment by wjdob** [comment]
Line 312 and 313 in Install script - adjust the link to reflect your Github master. Currently it points to my fork :)

**Comment by wjdob** [comment]
image

I suspect that line 307 may need to be wrapped to wait until Remove-Item completes. My computer has SSD, but I can imagine that on a HDD-based system the seek-time may cause too long of a delay when scanning sub-directories.

**Pull request closed without merging**
